name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.48.147.207 << 'EOF'
            cd /home/ubuntu/MT-MT-QUIZ-Aife-Edutech 
            git pull origin main  
            cd Backend-Aifer-Edutech  
            yarn install  
            yarn build  
            pm2 restart autonomize-ai-backend  
          EOF

      - name: Delete Frontend folder on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.48.147.207 << 'EOF'
            rm -rf /home/ubuntu/MT-MT-QUIZ-Aife-Edutech/Frontend-Aifer-Edutech  
          EOF
